
version: '3.8'
services:

  faraday:
    image: eureka/jupyterlab:0.0.1-bookworm-slim
    container_name: Faraday
    hostname: faraday
    ports:
      - 1022:22
      - 1088:8888
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - faraday_home:/home/eureka
      - faraday_ssh:/etc/ssh
    build:
      context: .
      dockerfile: Dockerfile


  darwin:
    image: eureka/jupyterlab:0.0.1-bookworm-slim
    container_name: Darwin
    hostname: darwin
    ports:
      - 1122:22
      - 1188:8888
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - darwin_home:/home/eureka
      - darwin_ssh:/etc/ssh

  euler:
    image: eureka/jupyterlab:0.0.1-bookworm-slim
    container_name: Euler
    hostname: euler
    ports:
      - 1222:22
      - 1288:8888
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - euler_home:/home/eureka
      - euler_ssh:/etc/ssh

  arkhimedes:
    image: eureka/jupyterlab:0.0.1-bookworm-slim
    container_name: Arkhimedes
    hostname: arkhimedes
    ports:
      - 1322:22
      - 1388:8888
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - arkhimedes_home:/home/eureka
      - arkhimedes_ssh:/etc/ssh

  asimov:
    image: eureka/jupyterlab:0.0.1-bookworm-slim
    container_name: Asimov
    hostname: asimov
    ports:
      - 1422:22
      - 1488:8888
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - asimov_home:/home/eureka
      - asimov_ssh:/etc/ssh

volumes:
  faraday_home:
  faraday_ssh:
  darwin_home:
  darwin_ssh:
  euler_home:
  euler_ssh:
  arkhimedes_home:
  arkhimedes_ssh:
  asimov_home:
  asimov_ssh:
