
version: '3.8'
services:

  juno:
    image: eureka/jupyterlab:0.0.1-bookworm-slim
    container_name: Juno
    hostname: juno
    ports:
      - 1022:22
      - 1088:8888
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - juno_home:/home/eureka
      - juno_ssh:/etc/ssh
    build:
      context: .
      dockerfile: Dockerfile


  io:
    image: eureka/jupyterlab:0.0.1-bookworm-slim
    container_name: Io
    hostname: io
    ports:
      - 1122:22
      - 1188:8888
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - io_home:/home/eureka
      - io_ssh:/etc/ssh

  europa:
    image: eureka/jupyterlab:0.0.1-bookworm-slim
    container_name: Europa
    hostname: europa
    ports:
      - 1222:22
      - 1288:8888
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - europa_home:/home/eureka
      - europa_ssh:/etc/ssh

  ganymede:
    image: eureka/jupyterlab:0.0.1-bookworm-slim
    container_name: Ganymede
    hostname: ganymede
    ports:
      - 1322:22
      - 1388:8888
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - ganymede_home:/home/eureka
      - ganymede_ssh:/etc/ssh

  callisto:
    image: eureka/jupyterlab:0.0.1-bookworm-slim
    container_name: Callisto
    hostname: callisto
    ports:
      - 1422:22
      - 1488:8888
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - callisto_home:/home/eureka
      - callisto_ssh:/etc/ssh

  caleb:
    image: eureka/jupyterlab:0.0.1-bookworm-slim
    container_name: Caleb
    hostname: caleb
    ports:
      - 1522:22
      - 1588:8888
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - caleb_home:/home/eureka
      - caleb_ssh:/etc/ssh

  ceballos:
    image: eureka/jupyterlab:0.0.1-bookworm-slim
    container_name: Ceballos
    hostname: ceballos
    ports:
      - 1622:22
      - 1688:8888
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - ceballos_home:/home/eureka
      - ceballos_ssh:/etc/ssh

  julia:
    image: eureka/jupyterlab:0.0.1-bookworm-slim
    container_name: Julia
    hostname: julia
    ports:
      - 1722:22
      - 1788:8888
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - julia_home:/home/eureka
      - julia_ssh:/etc/ssh

  irene:
    image: eureka/jupyterlab:0.0.1-bookworm-slim
    container_name: Irene
    hostname: irene
    ports:
      - 1822:22
      - 1888:8888
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - irene_home:/home/eureka
      - irene_ssh:/etc/ssh

  ivann:
    image: eureka/jupyterlab:0.0.1-bookworm-slim
    container_name: Ivann
    hostname: ivann
    ports:
      - 1922:22
      - 1988:8888
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - ivann_home:/home/eureka
      - ivann_ssh:/etc/ssh

  bruno:
    image: eureka/jupyterlab:0.0.1-bookworm-slim
    container_name: Bruno
    hostname: bruno
    ports:
      - 2022:22
      - 2088:8888
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - bruno_home:/home/eureka
      - bruno_ssh:/etc/ssh

  max:
    image: eureka/jupyterlab:0.0.1-bookworm-slim
    container_name: Max
    hostname: max
    ports:
      - 2122:22
      - 2188:8888
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - max_home:/home/eureka
      - max_ssh:/etc/ssh

  iyari:
    image: eureka/jupyterlab:0.0.1-bookworm-slim
    container_name: Iyari
    hostname: iyari
    ports:
      - 2222:22
      - 2288:8888
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - iyari_home:/home/eureka
      - iyari_ssh:/etc/ssh

  axel:
    image: eureka/jupyterlab:0.0.1-bookworm-slim
    container_name: Axel
    hostname: axel
    ports:
      - 2322:22
      - 2388:8888
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - axel_home:/home/eureka
      - axel_ssh:/etc/ssh

volumes:
  juno_home:
  juno_ssh:
  io_home:
  io_ssh:
  europa_home:
  europa_ssh:
  ganymede_home:
  ganymede_ssh:
  callisto_home:
  callisto_ssh:
  caleb_home:
  caleb_ssh:
  ceballos_home:
  ceballos_ssh:
  julia_home:
  julia_ssh:
  irene_home:
  irene_ssh:
  ivann_home:
  ivann_ssh:
  bruno_home:
  bruno_ssh:
  max_home:
  max_ssh:
  iyari_home:
  iyari_ssh:
  axel_home:
  axel_ssh:
