
services:

  juno:
    image: eureka/jupyterlab:0.0.2-bookworm-slim
    container_name: Juno
    hostname: juno
    ports:
      - 1022:22
      - 1088:8888
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - juno_home:/home/eureka
      - juno_ssh:/etc/ssh
    build:
      context: .
      dockerfile: Dockerfile


  io:
    image: eureka/jupyterlab:0.0.2-bookworm-slim
    container_name: Io
    hostname: io
    ports:
      - 1122:22
      - 1188:8888
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - io_home:/home/eureka
      - io_ssh:/etc/ssh

  europa:
    image: eureka/jupyterlab:0.0.2-bookworm-slim
    container_name: Europa
    hostname: europa
    ports:
      - 1222:22
      - 1288:8888
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - europa_home:/home/eureka
      - europa_ssh:/etc/ssh

  ganymede:
    image: eureka/jupyterlab:0.0.2-bookworm-slim
    container_name: Ganymede
    hostname: ganymede
    ports:
      - 1322:22
      - 1388:8888
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - ganymede_home:/home/eureka
      - ganymede_ssh:/etc/ssh

  callisto:
    image: eureka/jupyterlab:0.0.2-bookworm-slim
    container_name: Callisto
    hostname: callisto
    ports:
      - 1422:22
      - 1488:8888
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - callisto_home:/home/eureka
      - callisto_ssh:/etc/ssh

volumes:
  juno_home:
  juno_ssh:
  io_home:
  io_ssh:
  europa_home:
  europa_ssh:
  ganymede_home:
  ganymede_ssh:
  callisto_home:
  callisto_ssh:
