version: '3.8'      # Versión de la sintaxis del archivo Docker Compose.
services:           # Define los servicios que se ejecutarán en Docker Compose.
  jupyter:          # Nombre del servicio llamado "jupyter".
    image: incogniadev/jupyterlab:0.0.1-bookworm-slim # Imagen del contenedor.
    build:          # Configuración para construir la imagen del contenedor.
      context: .                        # Directorio de construcción.
      dockerfile: Dockerfile            # Archivo Dockerfile.
    container_name: JupyterLab          # Nombre del contenedor.
    hostname: jupyter                   # Nombre del host.
    ports:           # Mapeo de puertos entre el host y el contenedor.
      - 10022:22     # Mapea el puerto 10022 al 22 para SSH.
      - 18888:8888   # Mapea el puerto 18888 al 8888 para JupyterLab.
    environment:     # Variables de entorno para el contenedor.
      - TZ=America/Mexico_City          # Establece la zona horaria.
    tty: true        # Asigna una terminal pseudo-TTY al contenedor.
    stdin_open: true                    # Mantener STDIN abierto.
    restart: always                     # Reinicio automático.